---
Element:
  Block:
    title: Текстовый блок
  Cat:
    title: Каталог
  CatGroups:
    title: "Каталог: группы"
  CatNode:
    title: "Каталог: ресурс"
  CatNodes:
    title: "Каталог: ресурсы"
  Date:
    title: Дата
  Eval:
    title: Выполнение кода Ruby
  EventsTop:
   title: Последние события
  File:
    title: Файл
  Forms:
    title: Формы
  FormsForm:
    title: "Формы: форма"
  FormsInquiry:
    title: "Формы: опрос"
  Gallery:
    title: Галерея
  Image:
    title: Картинка
  MapTree:
    title: Карта сайта (дерево)
  News:
    title: Новости
  NewsArticle:
    title: "Новости: новость"
  NewsCalender:
    title: Календарь новостей
  NewsTop:
    title: "Новости: последние новости"
  Notice:
    title: Уведомление
  PageContent:
    title: Содержимое страницы
  PageLink:
    title: Ссылка
  PageTitle:
    title: Заголовок окна
  SiteMap: 
    title: Карта сайта
  SiteMapBeauty:
    title: Красивая карта сайта 
